os: linux
language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - node_modules
script:
  - yarn run clean-force
  - yarn run remove-modules
  - yarn run install-yarn
  - yarn test
  - yarn run test:coverage
  - yarn run build
  - yarn run audit-fix
before_deploy:
  - cd $TRAVIS_BUILD_DIR
deploy:
  provider: pages
  token: $github_token
  local_dir: build
  on:
    branch: master
