language: node_js
os: linux
node_js:
  - 'stable'
cache:
  directories:
    - node_modules
script:
  - yarn test
  - yarn run test:coverage
  - yarn run build
deploy:
  provider: pages
  cleanup: true
  token: $GITHUB_TOKEN
  keep_history: true
  strategy: git
  on:
    branch: master
