os: linux
language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - node_modules
script:
  - yarn test
  - yarn run test:coverage
  - yarn run build
deploy:
  provider: pages
  token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master
