language: node_js
os:
  - 'linux'
dist: xenial
node_js:
  - 'stable'
cache:
  directories:
    - node_modules
script:
  - yarn test
  - yarn run test:coverage
  - yarn run build
deploy:
  provider: pages
  cleanup: false
  token: $GITHUB_TOKEN
  keep_history: true
  strategy: git
  local_dir: ./build
  edge: true
  on:
    branch: master
